[project]
name = "p1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
	"requests",
	"pathlib",
	"ruff>=0.11.11",
	"aiohttp>=3.12.4",
	"httpx>=0.28.1",
	"ujson>=5.10.0",
	"parsel>=1.10.0",
]
